import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Translations
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    'welcome': 'Bienvenue',
    'logout': 'Déconnexion',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'search': 'Rechercher',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'add': 'Ajouter',
    'close': 'Fermer',
    'confirm': 'Confirmer',
    'yes': 'Oui',
    'no': 'Non',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'actions': 'Actions',
    'status': 'Statut',
    'name': 'Nom',
    'date': 'Date',
    'time': 'Heure',
    'type': 'Type',
    'details': 'Détails',
    'description': 'Description',
    'notes': 'Notes',
    'filter': 'Filtrer',
    'sort': 'Trier',
    'export': 'Exporter',
    'import': 'Importer',
    'download': 'Télécharger',
    'upload': 'Téléverser',
    'print': 'Imprimer',
    
    // Navigation
    'dashboard': 'Tableau de bord',
    'appointments': 'Rendez-vous',
    'consultations': 'Consultations',
    'patients': 'Patients',
    'revenue': 'Revenus',
    'chat': 'Messages',
    'calendar': 'Calendrier',
    'reports': 'Rapports',
    'statistics': 'Statistiques',
    
    // User & Auth
    'email': 'Email',
    'password': 'Mot de passe',
    'sign_in': 'Se connecter',
    'sign_up': 'S\'inscrire',
    'sign_out': 'Déconnexion',
    'forgot_password': 'Mot de passe oublié?',
    'remember_me': 'Se souvenir de moi',
    'medical_management': 'Gestion intelligente de cabinet médical',
    'no_account': 'Pas encore de compte ?',
    'create_doctor_account': 'Créer un compte Médecin',
    'create_secretary_account': 'Créer un compte Secrétaire',
    'demo_accounts': 'Comptes de démonstration :',
    'admin': 'Admin',
    'doctor': 'Médecin',
    'secretary': 'Secrétaire',
    
    // Languages
    'language': 'Langue',
    'french': 'Français',
    'arabic': 'العربية',
    'english': 'English',
    'change_language': 'Changer la langue',
    
    // Calendar / Appointments
    'Planning_of':'Plan du',
    'rendez-vous_programmés':'rendez-vous programmés',
    'new_appointment': 'Nouveau Rendez-vous',
    'appointment_details': 'Détails du Rendez-vous',
    'today_appointments': 'RDV Aujourd\'hui',
    'upcoming_appointments': 'Prochains RDV',
    'past_appointments': 'RDV Passés',
    'appointment_time': 'Heure du RDV',
    'appointment_type': 'Type de RDV',
    'appointment_status': 'Statut du RDV',
    'patient_name': 'Nom du patient',
    'patient_phone': 'Téléphone',
    'patient_email': 'Email du patient',
    'birth_date': 'Date de naissance',
    'age': 'Âge',
    'gender': 'Genre',
    'male': 'Masculin',
    'female': 'Féminin',
    'address': 'Adresse',
    'profession': 'Profession',
    'country': 'Pays',
    'region': 'Région',
    'city': 'Ville',
    'select_country': 'Sélectionner un pays',
    'select_region': 'Sélectionner une région',
    'select_profession': 'Sélectionner une profession',
    'select_first_country': 'Sélectionner d\'abord un pays',
    'please_select_country_first': 'Veuillez d\'abord sélectionner un pays',
    'regions_available': 'région(s) disponible(s) pour',
    'professions_available': 'profession(s) disponible(s)',
    'selected': 'Sélectionné',
    
    // Appointment Types & Status
    'consultation': 'Consultation',
    'control': 'Contrôle',
    'follow_up': 'Suivi',
    'emergency': 'Urgence',
    'confirmed': 'Confirmé',
    'pending': 'En attente',
    'cancelled': 'Annulé',
    'completed': 'Terminé',
    'no_show': 'Absent',
    'confirm_appointment': 'Confirmer le RDV',
    'cancel_appointment': 'Annuler le RDV',
    'reschedule_appointment': 'Reporter le RDV',
    
    // Countries
    'tunisia': 'Tunisie',
    'libya': 'Libye',
    'algeria': 'Algérie',
    'morocco': 'Maroc',
    'egypt': 'Égypte',
    'other': 'Autre',
    
    // Patients
    'patient_list': 'Liste des Patients',
    'patient_info': 'Informations Patient',
    'patient_details': 'Détails du Patient',
    'medical_history': 'Historique Médical',
    'add_patient': 'Ajouter Patient',
    'edit_patient': 'Modifier Patient',
    'delete_patient': 'Supprimer Patient',
    'total_patients': 'Patients Totaux',
    'new_patients': 'Nouveaux Patients',
    'active_patients': 'Patients Actifs',
    'patient_since': 'Patient depuis',
    'last_visit': 'Dernière visite',
    'next_appointment': 'Prochain RDV',
    'no_patients': 'Aucun patient',
    'search_patients': 'Rechercher des patients',
    'patient_added': 'Patient ajouté avec succès',
    'patient_updated': 'Patient mis à jour',
    'patient_deleted': 'Patient supprimé',
    
    // Consultations
    'consultation_notes': 'Notes de Consultation',
    'diagnosis': 'Diagnostic',
    'prescription': 'Ordonnance',
    'treatment': 'Traitement',
    'symptoms': 'Symptômes',
    'vital_signs': 'Signes Vitaux',
    'blood_pressure': 'Tension Artérielle',
    'heart_rate': 'Fréquence Cardiaque',
    'temperature': 'Température',
    'weight': 'Poids',
    'height': 'Taille',
    'start_consultation': 'Démarrer Consultation',
    'end_consultation': 'Terminer Consultation',
    'save_consultation': 'Enregistrer Consultation',
    'consultation_history': 'Historique Consultations',
    'no_consultations': 'Aucune consultation',
    'ai_assistant': 'Assistant IA',
    'ai_suggestions': 'Suggestions IA',
    
    // Revenue / Financial
    'total_revenue': 'Revenu Total',
    'monthly_revenue': 'Revenus Mensuels',
    'daily_revenue': 'Revenus Journaliers',
    'yearly_revenue': 'Revenus Annuels',
    'payment_method': 'Mode de Paiement',
    'cash': 'Espèces',
    'credit_card': 'Carte Bancaire',
    'bank_transfer': 'Virement Bancaire',
    'insurance': 'Assurance',
    'amount': 'Montant',
    'paid': 'Payé',
    'unpaid': 'Non payé',
    'partial': 'Partiel',
    'payment_status': 'Statut Paiement',
    'invoice': 'Facture',
    'receipt': 'Reçu',
    'generate_invoice': 'Générer Facture',
    'revenue_statistics': 'Statistiques des Revenus',
    'monthly_comparison': 'Comparaison Mensuelle',
    'payment_history': 'Historique Paiements',
    
    // Chat / Messages
    'messages': 'Messages',
    'new_message': 'Nouveau Message',
    'send_message': 'Envoyer',
    'type_message': 'Tapez un message...',
    'attach_file': 'Joindre un fichier',
    'no_messages': 'Aucun message',
    'chat_with_doctor': 'Chat avec médecin',
    'chat_with_secretary': 'Chat avec secrétaire',
    'chat_with_admin': 'Chat avec admin',
    'online': 'En ligne',
    'offline': 'Hors ligne',
    'typing': 'En train d\'écrire...',
    'seen': 'Vu',
    'delivered': 'Livré',
    'sent': 'Envoyé',
    'message_deleted': 'Message supprimé',
    'delete_message': 'Supprimer le message',
    'edit_message': 'Modifier le message',
    'file_attached': 'Fichier joint',
    
    // Dashboard Stats
    'appointments_overview': 'Aperçu des Rendez-vous',
    'recent_patients': 'Patients Récents',
    'patient_satisfaction': 'Satisfaction Patient',
    'pending_appointments': 'RDV en Attente',
    'confirmed_today': 'Confirmés Aujourd\'hui',
    'total_doctors': 'Médecins Totaux',
    'active_users': 'Utilisateurs Actifs',
    'system_revenue': 'Revenus Système',
    'doctors_management': 'Gestion des Médecins',
    
    // Time & Dates
    'today': 'Aujourd\'hui',
    'yesterday': 'Hier',
    'tomorrow': 'Demain',
    'this_week': 'Cette semaine',
    'this_month': 'Ce mois',
    'this_year': 'Cette année',
    'last_week': 'Semaine dernière',
    'last_month': 'Mois dernier',
    'last_year': 'Année dernière',
    'monday': 'Lundi',
    'tuesday': 'Mardi',
    'wednesday': 'Mercredi',
    'thursday': 'Jeudi',
    'friday': 'Vendredi',
    'saturday': 'Samedi',
    'sunday': 'Dimanche',
    'january': 'Janvier',
    'february': 'Février',
    'march': 'Mars',
    'april': 'Avril',
    'may': 'Mai',
    'june': 'Juin',
    'july': 'Juillet',
    'august': 'Août',
    'september': 'Septembre',
    'october': 'Octobre',
    'november': 'Novembre',
    'december': 'Décembre',
    
    // Status & Actions
    'active': 'Actif',
    'inactive': 'Inactif',
    'suspended': 'Suspendu',
    'view_details': 'Voir Détails',
    'show_more': 'Voir plus',
    'show_less': 'Voir moins',
    'select_all': 'Tout sélectionner',
    'deselect_all': 'Tout désélectionner',
    'refresh': 'Actualiser',
    'back': 'Retour',
    'next': 'Suivant',
    'previous': 'Précédent',
    'continue': 'Continuer',
    'finish': 'Terminer',
    'submit': 'Soumettre',
    'reset': 'Réinitialiser',
    'clear': 'Effacer',
    
    // Notifications
    'notifications': 'Notifications',
    'no_notifications': 'Aucune notification',
    'mark_as_read': 'Marquer comme lu',
    'mark_all_as_read': 'Tout marquer comme lu',
    'new_notification': 'Nouvelle notification',
    
    // Errors & Validation
    'field_required': 'Ce champ est requis',
    'invalid_email': 'Email invalide',
    'invalid_phone': 'Numéro de téléphone invalide',
    'password_too_short': 'Mot de passe trop court',
    'passwords_dont_match': 'Les mots de passe ne correspondent pas',
    'something_went_wrong': 'Une erreur s\'est produite',
    'try_again': 'Réessayer',
    'operation_successful': 'Opération réussie',
    'operation_failed': 'Opération échouée',
    
    // Misc
    'welcome_back': 'Bon retour',
    'good_morning': 'Bonjour',
    'good_afternoon': 'Bon après-midi',
    'good_evening': 'Bonsoir',
    'have_a_nice_day': 'Bonne journée',
    'dr': 'Dr.',
    'mr': 'M.',
    'mrs': 'Mme',
    'ms': 'Mlle',
    
    // Calendar specific
    'no_appointments': 'Aucun rendez-vous',
    'click_new_appointment_to_add': 'Cliquez sur "Nouveau rendez-vous" pour ajouter un patient',
    'edit_appointment': 'Modifier le rendez-vous',
    'appointment_saved': 'Rendez-vous enregistré avec succès',
    'new_patient': 'Nouveau patient',
    'existing_patient': 'Patient existant',
    'search_existing_patient': 'Rechercher un patient existant...',
    'payment_type': 'Type de paiement',
    'payment_normal': 'Normal',
    'payment_cnam': 'CNAM',
    'payment_insurance': 'Assurance',
    'payment_free': 'Gratuit',
    'tariff': 'Tarif',
    'amount_paid_label': 'Montant payé',
    'delete_appointment_confirm': 'Voulez-vous vraiment supprimer ce rendez-vous ?',
    'appointment_deleted': 'Rendez-vous supprimé',
    'appointment_confirmed': 'Rendez-vous confirmé',
    
    // Consultations specific
    'consultations_confirmed': 'Consultations confirmées',
    'confirmed_appointments_list': 'Liste des rendez-vous confirmés, classés du plus récent au plus ancien',
    'patient_file': 'Dossier patient',
    'update_patient': 'Modifier',
    'save_changes': 'Enregistrer',
    'return': 'Retour',
    'years_old': 'ans',
    'chronic_diseases': 'Maladies chroniques',
    'medical_history': 'Historique médical',
    'previous_consultations': 'Consultations précédentes',
    'new_consultation': 'Nouvelle consultation',
    'prescription_label': 'Ordonnance',
    'analysis_requested': 'Analyses demandées',
    'imaging_requested': 'Imagerie demandée',
    'clinical_notes': 'Notes cliniques',
    'save_consultation': 'Enregistrer la consultation',
    'consultation_saved': 'Consultation enregistrée avec succès',
    'referral_letter': 'Lettre d\'orientation',
    'files_attached': 'Fichiers attachés',
    'add_file': 'Ajouter un fichier',
    'no_files': 'Aucun fichier attaché',
    'click_add_file': 'Cliquez sur "Ajouter un fichier" pour commencer',
    'view': 'Afficher',
    'rename': 'Renommer',
    'file_renamed': 'Fichier renommé avec succès',
    'file_deleted': 'Fichier supprimé avec succès',
    'delete_file_confirm': 'Êtes-vous sûr de vouloir supprimer ce fichier ?',
    'patient_info_updated': 'Informations patient mises à jour avec succès',
    
    // Professions
    'select_profession_placeholder': 'Sélectionner une profession',
    'medical_health_sector': 'Secteur Médical & Santé',
    'profession_doctor': 'Médecin',
    'profession_nurse': 'Infirmier(ère)',
    'profession_pharmacist': 'Pharmacien(ne)',
    'profession_dentist': 'Dentiste',
    'education_sector': 'Secteur Éducation',
    'profession_teacher': 'Enseignant(e)',
    'profession_professor': 'Professeur',
    'profession_student': 'Étudiant(e)',
    'engineering_tech_sector': 'Ingénierie & Technologie',
    'profession_engineer': 'Ingénieur',
    'profession_developer': 'Développeur',
    'profession_technician': 'Technicien',
    'business_management_sector': 'Commerce & Gestion',
    'profession_manager': 'Manager',
    'profession_accountant': 'Comptable',
    'profession_entrepreneur': 'Entrepreneur',
    'public_services_sector': 'Services Publics',
    'profession_civil_servant': 'Fonctionnaire',
    'profession_police': 'Policier',
    'profession_firefighter': 'Pompier',
    'arts_culture_sector': 'Arts & Culture',
    'profession_artist': 'Artiste',
    'profession_musician': 'Musicien',
    'profession_writer': 'Écrivain',
    'other_professions': 'Autres Professions',
    'profession_retired': 'Retraité(e)',
    'profession_housewife': 'Au foyer',
    'profession_unemployed': 'Sans emploi',
    'profession_other': 'Autre',
    
    // Countries detailed
    'maghreb_countries': 'Pays du Maghreb',
    'middle_east_countries': 'Pays du Moyen-Orient',
    'european_countries': 'Pays Européens',
    'tunisia_full': 'Tunisie - République Tunisienne',
    'algeria_full': 'Algérie - République Algérienne',
    'morocco_full': 'Maroc - Royaume du Maroc',
    'libya_full': 'Libye - État de Libye',
    'mauritania_full': 'Mauritanie - République Islamique de Mauritanie',
    
    // Regions
    'tunisia_regions': 'Régions de Tunisie',
    'region_tunis': 'Tunis',
    'region_ariana': 'Ariana',
    'region_ben_arous': 'Ben Arous',
    'region_manouba': 'Manouba',
    'region_sfax': 'Sfax',
    'region_sousse': 'Sousse',
    'region_nabeul': 'Nabeul',
    
    // Consultation details
    'consultation_date': 'Date de consultation',
    'consultation_type': 'Type de consultation',
    'reason_for_visit': 'Motif de visite',
    'examination': 'Examen',
    'treatment_plan': 'Plan de traitement',
    'follow_up_date': 'Date de suivi',
    'medications': 'Médicaments',
    'dosage': 'Dosage',
    'frequency': 'Fréquence',
    'duration': 'Durée',
    'instructions': 'Instructions',
    'side_effects': 'Effets secondaires',
    'allergies': 'Allergies',
    'current_medications': 'Médicaments actuels',
    'medical_conditions': 'Conditions médicales',
    'family_history': 'Antécédents familiaux',
    'social_history': 'Antécédents sociaux',
    'surgical_history': 'Antécédents chirurgicaux',
    
    // AI Assistant
    'ask_ai': 'Demander à l\'IA',
    'ai_analyzing': 'IA en cours d\'analyse...',
    'ai_suggestion': 'Suggestion IA',
    'ai_diagnosis_help': 'Aide au diagnostic',
    'ai_treatment_suggestions': 'Suggestions de traitement',
    'ai_drug_interactions': 'Interactions médicamenteuses',
    'ai_medical_references': 'Références médicales',
    'type_your_question': 'Tapez votre question...',
    'send': 'Envoyer',
    
    // File management
    'file_name': 'Nom du fichier',
    'file_size': 'Taille',
    'file_type': 'Type',
    'uploaded_date': 'Date d\'upload',
    'uploaded_by': 'Uploadé par',
    'download_file': 'Télécharger',
    'delete_file': 'Supprimer',
    'rename_file': 'Renommer',
    'preview_file': 'Prévisualiser',
    'upload_file': 'Téléverser un fichier',
    'drag_drop_files': 'Glissez-déposez vos fichiers ici',
    'or_click_to_browse': 'ou cliquez pour parcourir',
    'supported_formats': 'Formats supportés',
    'max_file_size': 'Taille maximale',
    
    // Patients View
    'all_patients': 'Tous les patients',
    'patients_list': 'Liste des patients',
    'patient_card': 'Carte patient',
    'patient_number': 'N° Patient',
    'registration_date': 'Date d\'inscription',
    'total_consultations': 'Total consultations',
    'last_consultation': 'Dernière consultation',
    'patient_status': 'Statut patient',
    'contact_info': 'Informations de contact',
    'emergency_contact': 'Contact d\'urgence',
    'insurance_info': 'Informations d\'assurance',
    'insurance_number': 'N° d\'assurance',
    'insurance_provider': 'Fournisseur d\'assurance',
    'policy_number': 'N° de police',
    'expiry_date': 'Date d\'expiration',
    
    // Revenue View
    'revenue_overview': 'Aperçu des revenus',
    'total_earnings': 'Gains totaux',
    'this_month_revenue': 'Revenus du mois',
    'last_month_revenue': 'Revenus mois dernier',
    'revenue_growth': 'Croissance des revenus',
    'payment_received': 'Paiement reçu',
    'payment_pending': 'Paiement en attente',
    'payment_details': 'Détails du paiement',
    'transaction_history': 'Historique des transactions',
    'transaction_date': 'Date de transaction',
    'transaction_type': 'Type de transaction',
    'transaction_amount': 'Montant',
    'transaction_id': 'ID Transaction',
    'payment_for': 'Paiement pour',
    'revenue_by_month': 'Revenus par mois',
    'revenue_by_payment_type': 'Revenus par type de paiement',
    'revenue_statistics_detailed': 'Statistiques détaillées des revenus',
    'average_per_consultation': 'Moyenne par consultation',
    'consultations_count': 'Nombre de consultations',
    'paid_consultations': 'Consultations payées',
    'unpaid_consultations': 'Consultations non payées',
    
    // Profile & Settings
    'personal_information': 'Informations personnelles',
    'professional_information': 'Informations professionnelles',
    'account_settings': 'Paramètres du compte',
    'security_settings': 'Paramètres de sécurité',
    'change_password': 'Changer le mot de passe',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'update_profile': 'Mettre à jour le profil',
    'profile_updated': 'Profil mis à jour avec succès',
    'password_updated': 'Mot de passe mis à jour',
    'specialty': 'Spécialité',
    'license_number': 'N° de licence',
    'years_of_experience': 'Années d\'expérience',
    'education': 'Formation',
    'certifications': 'Certifications',
    'languages_spoken': 'Langues parlées',
    'clinic_address': 'Adresse du cabinet',
    'consultation_fees': 'Honoraires de consultation',
    'working_hours': 'Heures de travail',
    'availability': 'Disponibilité',
    
    // Secretary Dashboard
    'secretary_dashboard': 'Tableau de bord Secrétaire',
    'manage_appointments': 'Gérer les rendez-vous',
    'book_appointment': 'Prendre un rendez-vous',
    'appointment_calendar': 'Calendrier des rendez-vous',
    'patient_registration': 'Inscription patient',
    'appointments_today': 'Rendez-vous aujourd\'hui',
    'appointments_this_week': 'RDV cette semaine',
    'waiting_room': 'Salle d\'attente',
    'checked_in': 'Enregistré',
    'check_in': 'Enregistrer',
    'check_out': 'Libérer',
    'waiting': 'En attente',
    'in_consultation': 'En consultation',
    'completed_today': 'Terminés aujourd\'hui',
    
    // Admin specific
    'admin_dashboard': 'Tableau de bord Admin',
    'system_overview': 'Vue d\'ensemble du système',
    'user_management': 'Gestion des utilisateurs',
    'doctor_management': 'Gestion des médecins',
    'secretary_management': 'Gestion des secrétaires',
    'add_doctor': 'Ajouter un médecin',
    'add_secretary': 'Ajouter une secrétaire',
    'activate_account': 'Activer le compte',
    'suspend_account': 'Suspendre le compte',
    'account_status': 'Statut du compte',
    'access_control': 'Contrôle d\'accès',
    'permissions': 'Permissions',
    'role': 'Rôle',
    'last_login': 'Dernière connexion',
    'account_created': 'Compte créé',
    
    // Time periods
    'daily': 'Quotidien',
    'weekly': 'Hebdomadaire',
    'monthly': 'Mensuel',
    'yearly': 'Annuel',
    'custom_range': 'Période personnalisée',
    'from_date': 'De',
    'to_date': 'À',
    'select_date': 'Sélectionner une date',
    'select_time': 'Sélectionner l\'heure',
    
    // Actions & Buttons
    'create': 'Créer',
    'update': 'Mettre à jour',
    'remove': 'Retirer',
    'restore': 'Restaurer',
    'archive': 'Archiver',
    'unarchive': 'Désarchiver',
    'duplicate': 'Dupliquer',
    'share': 'Partager',
    'copy': 'Copier',
    'paste': 'Coller',
    'undo': 'Annuler',
    'redo': 'Refaire',
    'select': 'Sélectionner',
    'deselect': 'Désélectionner',
    
    // Status messages
    'saved_successfully': 'Enregistré avec succès',
    'deleted_successfully': 'Supprimé avec succès',
    'updated_successfully': 'Mis à jour avec succès',
    'created_successfully': 'Créé avec succès',
    'operation_completed': 'Opération terminée',
    'please_wait': 'Veuillez patienter',
    'processing': 'Traitement en cours',
    'are_you_sure': 'Êtes-vous sûr ?',
    'cannot_be_undone': 'Cette action ne peut pas être annulée',
    'confirm_delete': 'Confirmer la suppression',
    'confirm_action': 'Confirmer l\'action',
    
    // Pagination
    'page': 'Page',
    'of': 'de',
    'items_per_page': 'Éléments par page',
    'showing': 'Affichage',
    'to': 'à',
    'results': 'résultats',
    'first_page': 'Première page',
    'last_page': 'Dernière page',
    'no_data': 'Aucune donnée',
    'no_results_found': 'Aucun résultat trouvé',
    
    // Patient names (example data translations)
    'patient_name_1': 'Mohamed Gharbi',
    'patient_name_2': 'Amira Ben Said',
    'patient_name_3': 'Youssef Hamdi',
    'patient_name_4': 'Salma Trabelsi',
    'patient_name_5': 'Karim Bouzid',
    'patient_name_6': 'Leila Mansour',
    'patient_name_7': 'Ahmed Touati',
    
    // Patient job titles
    'job_teacher': 'Enseignant',
    'job_pharmacist': 'Pharmacienne',
    'job_engineer': 'Ingénieur',
    'job_merchant': 'Commerçante',
    'job_lawyer': 'Avocat',
    'job_nurse': 'Infirmière',
    'job_accountant': 'Comptable',
    
    // Patient addresses
    'address_tunis_bourguiba': 'Avenue Bourguiba, Tunis',
    'address_sousse_nov7': 'Boulevard 7 Novembre, Sousse',
    'address_sfax_republique': 'Rue de la République, Sfax',
    'address_monastir_liberte': 'Avenue de la Liberté, Monastir',
    'address_bizerte_thameur': 'Rue Habib Thameur, Bizerte',
    'address_nabeul_independence': 'Avenue de l\'Indépendance, Nabeul',
    'address_gabes_principale': 'Rue Principale, Gabès',
    
    // Medical conditions/diseases
    'disease_hypertension': 'Hypertension',
    'disease_diabetes_type2': 'Diabète type 2',
    'disease_chronic_migraine': 'Migraine chronique',
    'disease_arthritis': 'Arthrose',
    'disease_asthma': 'Asthme',
    'disease_thyroid': 'Troubles thyroïdiens',
    
    // Consultation notes examples
    'note_patient_stable': 'Patient stable, contrôle dans 3 mois',
    'note_crisis_decreasing': 'Fréquence des crises en diminution',
    'note_regular_followup': 'Suivi régulier recommandé',
    
    // Prescriptions examples
    'prescription_metformin': 'Metformine 500mg - 2x/jour',
    'prescription_ramipril': 'Ramipril 5mg - 1x/jour',
    'prescription_sumatriptan': 'Sumatriptan 50mg - en cas de crise',
    
    // Analysis types
    'analysis_glucose': 'Glycémie à jeun',
    'analysis_hba1c': 'HbA1c',
    'analysis_cholesterol': 'Bilan lipidique',
    'analysis_blood_count': 'Numération formule sanguine',
    
    // Profile page specific
    'edit_profile': 'Modifier le profil',
    'profile_picture': 'Photo de profil',
    'upload_picture': 'Télécharger une photo',
    'first_name': 'Prénom',
    'last_name': 'Nom',
    'full_name': 'Nom complet',
    'bio': 'Biographie',
    'about_me': 'À propos de moi',
    'professional_title': 'Titre professionnel',
    'medical_specialty': 'Spécialité médicale',
    'practice_since': 'Exerce depuis',
    'consultation_price': 'Prix de consultation',
    'office_phone': 'Téléphone cabinet',
    'mobile_phone': 'Téléphone mobile',
    'office_hours': 'Heures de bureau',
    'monday_friday': 'Lundi - Vendredi',
    'saturday': 'Samedi',
    'closed': 'Fermé',
    'morning': 'Matin',
    'afternoon': 'Après-midi',
    'evening': 'Soir',
  },
  
  ar: {
    // Common
    'welcome': 'مرحبا',
    'logout': 'تسجيل الخروج',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'search': 'بحث',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'yes': 'نعم',
    'no': 'لا',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجح',
    'actions': 'إجراءات',
    'status': 'الحالة',
    'name': 'الاسم',
    'date': 'التاريخ',
    'time': 'الوقت',
    'type': 'النوع',
    'details': 'التفاصيل',
    'description': 'الوصف',
    'notes': 'ملاحظات',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'export': 'تصدير',
    'import': 'استيراد',
    'download': 'تحميل',
    'upload': 'رفع',
    'print': 'طباعة',
    
    // Navigation
    'dashboard': 'لوحة التحكم',
    'appointments': 'المواعد',
    'consultations': 'الاستشارات',
    'patients': 'المرضى',
    'revenue': 'الإيرادات',
    'chat': 'الرسائل',
    'calendar': 'التقويم',
    'reports': 'التقارير',
    'statistics': 'الإحصائيات',
    
    // User & Auth
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'sign_in': 'تسجيل الدخول',
    'sign_up': 'التسجيل',
    'sign_out': 'تسجيل الخروج',
    'forgot_password': 'نسيت كلمة المرور؟',
    'remember_me': 'تذكرني',
    'medical_management': 'إدارة ذكية للعيادة الطبية',
    'no_account': 'ليس لديك حساب؟',
    'create_doctor_account': 'إنشاء حساب طبيب',
    'create_secretary_account': 'إنشاء حساب سكرتيرة',
    'demo_accounts': 'حسابات تجريبية:',
    'admin': 'مسؤول',
    'doctor': 'طبيب',
    'secretary': 'سكرتيرة',
    
    // Languages
    'language': 'اللغة',
    'french': 'Français',
    'arabic': 'العربية',
    'english': 'English',
    'change_language': 'تغيير اللغة',
    
    // Calendar / Appointments
    'Planning_of':'خطةاليوم',
    'rendez-vous_programmés':'المواعيد المجدولة',
    'new_appointment': 'موعد جديد',
    'appointment_details': 'تفاصيل الموعد',
    'today_appointments': 'مواعيد اليوم',
    'upcoming_appointments': 'المواعيد القادمة',
    'past_appointments': 'المواعيد السابقة',
    'appointment_time': 'وقت الموعد',
    'appointment_type': 'نوع الموعد',
    'appointment_status': 'حالة الموعد',
    'patient_name': 'اسم المريض',
    'patient_phone': 'الهاتف',
    'patient_email': 'البريد الإلكتروني للمريض',
    'birth_date': 'تاريخ الميلاد',
    'age': 'العمر',
    'gender': 'الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'address': 'العنوان',
    'profession': 'المهنة',
    'country': 'البلد',
    'region': 'المنطقة',
    'city': 'المدينة',
    'select_country': 'اختر البلد',
    'select_region': 'اختر المنطقة',
    'select_profession': 'اختر المهنة',
    'select_first_country': 'اختر البلد أولاً',
    'please_select_country_first': 'الرجاء اختيار البلد أولاً',
    'regions_available': 'منطقة متاحة لـ',
    'professions_available': 'مهنة متاحة',
    'selected': 'محدد',
    
    // Appointment Types & Status
    'consultation': 'استشارة',
    'control': 'مراقبة',
    'follow_up': 'متابعة',
    'emergency': 'طوارئ',
    'confirmed': 'مؤكد',
    'pending': 'معلق',
    'cancelled': 'ملغى',
    'completed': 'مكتمل',
    'no_show': 'غائب',
    'confirm_appointment': 'تأكيد الموعد',
    'cancel_appointment': 'إلغاء الموعد',
    'reschedule_appointment': 'إعادة جدولة الموعد',
    
    // Countries
    'tunisia': 'تونس',
    'libya': 'ليبيا',
    'algeria': 'الجزائر',
    'morocco': 'المغرب',
    'egypt': 'مصر',
    'other': 'آخر',
    
    // Patients
    'patient_list': 'قائمة المرضى',
    'patient_info': 'معلومات المريض',
    'patient_details': 'تفاصيل المريض',
    'medical_history': 'التاريخ الطبي',
    'add_patient': 'إضافة مريض',
    'edit_patient': 'تعديل مريض',
    'delete_patient': 'حذف مريض',
    'total_patients': 'إجمالي المرضى',
    'new_patients': 'مرضى جدد',
    'active_patients': 'مرضى نشطون',
    'patient_since': 'مريض منذ',
    'last_visit': 'آخر زيارة',
    'next_appointment': 'الموعد القادم',
    'no_patients': 'لا يوجد مرضى',
    'search_patients': 'البحث عن مرضى',
    'patient_added': 'تمت إضافة المريض بنجاح',
    'patient_updated': 'تم تحديث المريض',
    'patient_deleted': 'تم حذف المريض',
    
    // Consultations
    'consultation_notes': 'ملاحظات الاستشارة',
    'diagnosis': 'التشخيص',
    'prescription': 'الوصفة الطبية',
    'treatment': 'العلاج',
    'symptoms': 'الأعراض',
    'vital_signs': 'العلامات الحيوية',
    'blood_pressure': 'ضغط الدم',
    'heart_rate': 'معدل القلب',
    'temperature': 'درجة الحرارة',
    'weight': 'الوزن',
    'height': 'الطول',
    'start_consultation': 'بدء الاستشارة',
    'end_consultation': 'إنهاء الاستشارة',
    'save_consultation': 'حفظ الاستشارة',
    'consultation_history': 'تاريخ الاستشارات',
    'no_consultations': 'لا توجد استشارات',
    'ai_assistant': 'المساعد الذكي',
    'ai_suggestions': 'اقتراحات الذكاء الاصطناعي',
    
    // Revenue / Financial
    'total_revenue': 'إجمالي الإيرادات',
    'monthly_revenue': 'الإيرادات الشهرية',
    'daily_revenue': 'الإيرادات اليومية',
    'yearly_revenue': 'الإيرادات السنوية',
    'payment_method': 'طريقة الدفع',
    'cash': 'نقدا',
    'credit_card': 'بطاقة ائتمان',
    'bank_transfer': 'تحويل بنكي',
    'insurance': 'تأمين',
    'amount': 'المبلغ',
    'paid': 'مدفوع',
    'unpaid': 'غير مدفوع',
    'partial': 'جزئي',
    'payment_status': 'حالة الدفع',
    'invoice': 'فاتورة',
    'receipt': 'إيصال',
    'generate_invoice': 'إنشاء فاتورة',
    'revenue_statistics': 'إحصائيات الإيرادات',
    'monthly_comparison': 'مقارنة شهرية',
    'payment_history': 'تاريخ المدفوعات',
    
    // Chat / Messages
    'messages': 'الرسائل',
    'new_message': 'رسالة جديدة',
    'send_message': 'إرسال',
    'type_message': 'اكتب رسالة...',
    'attach_file': 'إرفاق ملف',
    'no_messages': 'لا توجد رسائل',
    'chat_with_doctor': 'الدردشة مع الطبيب',
    'chat_with_secretary': 'الدردشة مع السكرتيرة',
    'chat_with_admin': 'الدردشة مع المسؤول',
    'online': 'متصل',
    'offline': 'غير متصل',
    'typing': 'يكتب...',
    'seen': 'تمت المشاهدة',
    'delivered': 'تم التسليم',
    'sent': 'تم الإرسال',
    'message_deleted': 'تم حذف الرسالة',
    'delete_message': 'حذف الرسالة',
    'edit_message': 'تعديل الرسالة',
    'file_attached': 'ملف مرفق',
    
    // Dashboard Stats
    'appointments_overview': 'نظرة عامة على المواعيد',
    'recent_patients': 'المرضى الأخيرين',
    'patient_satisfaction': 'رضا المرضى',
    'pending_appointments': 'المواعيد المعلقة',
    'confirmed_today': 'مؤكد اليوم',
    'total_doctors': 'إجمالي الأطباء',
    'active_users': 'المستخدمون النشطون',
    'system_revenue': 'إيرادات النظام',
    'doctors_management': 'إدارة الأطباء',
    
    // Time & Dates
    'today': 'اليوم',
    'yesterday': 'أمس',
    'tomorrow': 'غدا',
    'this_week': 'هذا الأسبوع',
    'this_month': 'هذا الشهر',
    'this_year': 'هذا العام',
    'last_week': 'الأسبوع الماضي',
    'last_month': 'الشهر الماضي',
    'last_year': 'العام الماضي',
    'monday': 'الاثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    'sunday': 'الأحد',
    'january': 'يناير',
    'february': 'فبراير',
    'march': 'مارس',
    'april': 'أبريل',
    'may': 'مايو',
    'june': 'يونيو',
    'july': 'يوليو',
    'august': 'أغسطس',
    'september': 'سبتمبر',
    'october': 'أكتوبر',
    'november': 'نوفمبر',
    'december': 'ديسمبر',
    
    // Status & Actions
    'active': 'نشط',
    'inactive': 'غير نشط',
    'suspended': 'معلق',
    'view_details': 'عرض التفاصيل',
    'show_more': 'عرض المزيد',
    'show_less': 'عرض أقل',
    'select_all': 'تحديد الكل',
    'deselect_all': 'إلغاء تحديد الكل',
    'refresh': 'تحديث',
    'back': 'رجوع',
    'next': 'التالي',
    'previous': 'السابق',
    'continue': 'متابعة',
    'finish': 'إنهاء',
    'submit': 'إرسال',
    'reset': 'إعادة تعيين',
    'clear': 'مسح',
    
    // Notifications
    'notifications': 'الإشعارات',
    'no_notifications': 'لا توجد إشعارات',
    'mark_as_read': 'وضع علامة كمقروء',
    'mark_all_as_read': 'وضع علامة على الكل كمقروء',
    'new_notification': 'إشعار جديد',
    
    // Errors & Validation
    'field_required': 'هذا الحقل مطلوب',
    'invalid_email': 'البريد الإلكتروني غير صالح',
    'invalid_phone': 'رقم الهاتف غير صالح',
    'password_too_short': 'كلمة المرور قصيرة جداً',
    'passwords_dont_match': 'كلمات المرور غير متطابقة',
    'something_went_wrong': 'حدث خطأ ما',
    'try_again': 'حاول مرة أخرى',
    'operation_successful': 'العملية ناجحة',
    'operation_failed': 'فشلت العملية',
    
    // Misc
    'welcome_back': 'مرحبا بعودتك',
    'good_morning': 'صباح الخير',
    'good_afternoon': 'مساء الخير',
    'good_evening': 'مساء الخير',
    'have_a_nice_day': 'أتمنى لك يوماً سعيداً',
    'dr': 'د.',
    'mr': 'السيد',
    'mrs': 'السيدة',
    'ms': 'الآنسة',
    
    // Calendar specific
    'no_appointments': 'لا توجد مواعيد',
    'click_new_appointment_to_add': 'انقر على "موعد جديد" لإضافة مريض',
    'edit_appointment': 'تعديل الموعد',
    'appointment_saved': 'تم حفظ الموعد بنجاح',
    'new_patient': 'مريض جديد',
    'existing_patient': 'مريض موجود',
    'search_existing_patient': 'البحث عن مريض موجود...',
    'payment_type': 'نوع الدفع',
    'payment_normal': 'عادي',
    'payment_cnam': 'CNAM',
    'payment_insurance': 'تأمين',
    'payment_free': 'مجاني',
    'tariff': 'التعريفة',
    'amount_paid_label': 'المبلغ المدفوع',
    'delete_appointment_confirm': 'هل تريد حقاً حذف هذا الموعد؟',
    'appointment_deleted': 'تم حذف الموعد',
    'appointment_confirmed': 'تم تأكيد الموعد',
    
    // Consultations specific
    'consultations_confirmed': 'المواعيد المؤكدة',
    'confirmed_appointments_list': 'قائمة المواعيد المؤكدة، مرتبة من الأحدث إلى الأقدم',
    'patient_file': 'ملف المريض',
    'update_patient': 'تعديل',
    'save_changes': 'حفظ',
    'return': 'رجوع',
    'years_old': 'سنة',
    'chronic_diseases': 'الأمراض المزمنة',
    'medical_history': 'التاريخ الطبي',
    'previous_consultations': 'الاستشارات السابقة',
    'new_consultation': 'استشارة جديدة',
    'prescription_label': 'الوصفة الطبية',
    'analysis_requested': 'التحاليل المطلوبة',
    'imaging_requested': 'التصوير المطلوب',
    'clinical_notes': 'ملاحظات سريرية',
    'save_consultation': 'حفظ الاستشارة',
    'consultation_saved': 'تم حفظ الاستشارة بنجاح',
    'referral_letter': 'رسالة إحالة',
    'files_attached': 'الملفات المرفقة',
    'add_file': 'إضافة ملف',
    'no_files': 'لا توجد ملفات مرفقة',
    'click_add_file': 'انقر على "إضافة ملف" للبدء',
    'view': 'عرض',
    'rename': 'إعادة تسمية',
    'file_renamed': 'تمت إعادة تسمية الملف بنجاح',
    'file_deleted': 'تم حذف الملف بنجاح',
    'delete_file_confirm': 'هل أنت متأكد من حذف هذا الملف؟',
    'patient_info_updated': 'تم تحديث معلومات المريض بنجاح',
    
    // Professions
    'select_profession_placeholder': 'اختر مهنة',
    'medical_health_sector': 'القطاع الطبي والصحي',
    'profession_doctor': 'طبيب',
    'profession_nurse': 'ممرض/ممرضة',
    'profession_pharmacist': 'صيدلي/صيدلانية',
    'profession_dentist': 'طبيب أسنان',
    'education_sector': 'قطاع التعليم',
    'profession_teacher': 'معلم/معلمة',
    'profession_professor': 'أستاذ',
    'profession_student': 'طالب/طالبة',
    'engineering_tech_sector': 'الهندسة والتكنولوجيا',
    'profession_engineer': 'مهندس',
    'profession_developer': 'مطور',
    'profession_technician': 'فني',
    'business_management_sector': 'التجارة والإدارة',
    'profession_manager': 'مدير',
    'profession_accountant': 'محاسب',
    'profession_entrepreneur': 'رجل أعمال',
    'public_services_sector': 'الخدمات العامة',
    'profession_civil_servant': 'موظف حكومي',
    'profession_police': 'شرطي',
    'profession_firefighter': 'رجل إطفاء',
    'arts_culture_sector': 'الفنون والثقافة',
    'profession_artist': 'فنان',
    'profession_musician': 'موسيقي',
    'profession_writer': 'كاتب',
    'other_professions': 'مهن أخرى',
    'profession_retired': 'متقاعد/متقاعدة',
    'profession_housewife': 'ربة منزل',
    'profession_unemployed': 'عاطل عن العمل',
    'profession_other': 'أخرى',
    
    // Countries detailed
    'maghreb_countries': 'بلدان المغرب',
    'middle_east_countries': 'بلدان الشرق الأوسط',
    'european_countries': 'بلدان أوروبا',
    'tunisia_full': 'تونس - الجمهورية التونسية',
    'algeria_full': 'الجزائر - الجمهورية الجزائرية',
    'morocco_full': 'المغرب - المملكة المغربية',
    'libya_full': 'ليبيا - دولة ليبيا',
    'mauritania_full': 'موريتانيا - الجمهورية الإسلامية الموريتانية',
    
    // Regions
    'tunisia_regions': 'مناطق تونس',
    'region_tunis': 'تونس',
    'region_ariana': 'أريانا',
    'region_ben_arous': 'بن عروس',
    'region_manouba': 'منوبة',
    'region_sfax': 'صفاقس',
    'region_sousse': 'سوسة',
    'region_nabeul': 'نابل',
    
    // Consultation details
    'consultation_date': 'تاريخ الاستشارة',
    'consultation_type': 'نوع الاستشارة',
    'reason_for_visit': 'سبب الزيارة',
    'examination': 'فحص',
    'treatment_plan': 'خطة العلاج',
    'follow_up_date': 'تاريخ المتابعة',
    'medications': 'الأدوية',
    'dosage': 'جرعة',
    'frequency': 'تردد',
    'duration': 'مدة',
    'instructions': 'تعليمات',
    'side_effects': 'آثار جانبية',
    'allergies': 'حساسية',
    'current_medications': 'الأدوية الحالية',
    'medical_conditions': 'الظروف الطبية',
    'family_history': 'التاريخ العائلي',
    'social_history': 'التاريخ الاجتماعي',
    'surgical_history': 'التاريخ الجراحي',
    
    // AI Assistant
    'ask_ai': 'طلب من الذكاء الاصطناعي',
    'ai_analyzing': 'الذكاء الاصطناعي يحلل...',
    'ai_suggestion': 'اقتراح الذكاء الاصطناعي',
    'ai_diagnosis_help': 'مساعدة التشخيص',
    'ai_treatment_suggestions': 'اقتراحات العلاج',
    'ai_drug_interactions': 'تفاعلات الأدوية',
    'ai_medical_references': 'مرجعيات طبية',
    'type_your_question': 'اكتب سؤالك...',
    'send': 'إرسال',
    
    // File management
    'file_name': 'اسم الملف',
    'file_size': 'حجم الملف',
    'file_type': 'نوع الملف',
    'uploaded_date': 'تاريخ الرفع',
    'uploaded_by': 'رفعه',
    'download_file': 'تحميل الملف',
    'delete_file': 'حذف الملف',
    'rename_file': 'إعادة تسمية الملف',
    'preview_file': 'معاينة الملف',
    'upload_file': 'رفع ملف',
    'drag_drop_files': 'قم بسحب وإفلات الملفات هنا',
    'or_click_to_browse': 'أو انقر لتصفح',
    'supported_formats': 'التنسيقات المدعومة',
    'max_file_size': 'الحجم الأقصى للملف',
    
    // Patients View
    'all_patients': 'جميع المرضى',
    'patients_list': 'قائمة المرضى',
    'patient_card': 'بطاقة المريض',
    'patient_number': 'رقم المريض',
    'registration_date': 'تاريخ التسجيل',
    'total_consultations': 'إجمالي الاستشارات',
    'last_consultation': 'آخر استشارة',
    'patient_status': 'حالة المريض',
    'contact_info': 'معلومات الاتصال',
    'emergency_contact': 'اتصال الطوارئ',
    'insurance_info': 'معلومات التأمين',
    'insurance_number': 'رقم التأمين',
    'insurance_provider': 'شركة التأمين',
    'policy_number': 'رقم سياسة التأمين',
    'expiry_date': 'تاريخ الانتهاء',
    
    // Revenue View
    'revenue_overview': 'نظرة عامة على الإيرادات',
    'total_earnings': 'إجمالي الأرباح',
    'this_month_revenue': 'الإيرادات لهذا الشهر',
    'last_month_revenue': 'الإيرادات لشهر الماضي',
    'revenue_growth': 'نمو الإيرادات',
    'payment_received': 'الدفعات المستلمة',
    'payment_pending': 'الدفعات المعلقة',
    'payment_details': 'تفاصيل الدفع',
    'transaction_history': 'تاريخ المعاملات',
    'transaction_date': 'تاريخ المعاملة',
    'transaction_type': 'نوع المعاملة',
    'transaction_amount': 'قيمة المعاملة',
    'transaction_id': 'رقم المعاملة',
    'payment_for': 'دفع مقابل',
    'revenue_by_month': 'الإيرادات الشهرية',
    'revenue_by_payment_type': 'الإيرادات حسب نوع الدفع',
    'revenue_statistics_detailed': 'إحصائيات الإيرادات التفصيلية',
    'average_per_consultation': 'متوسط لكل استشارة',
    'consultations_count': 'عدد الاستشارات',
    'paid_consultations': 'استشارات مدفوعة',
    'unpaid_consultations': 'استشارات غير مدفوعة',
    
    // Profile & Settings
    'personal_information': 'معلومات شخصية',
    'professional_information': 'معلومات المهنية',
    'account_settings': 'إعدادات الحساب',
    'security_settings': 'إعدادات الأمان',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'update_profile': 'تحديث الملف الشخصي',
    'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
    'password_updated': 'تم تحديث كلمة المرور',
    'specialty': 'التخصص',
    'license_number': 'رقم الرخصة',
    'years_of_experience': 'سنوات الخبرة',
    'education': 'التعليم',
    'certifications': 'الشهادات',
    'languages_spoken': 'اللغات التي تتحدثها',
    'clinic_address': 'عنوان العيادة',
    'consultation_fees': 'رسوم الاستشارة',
    'working_hours': 'ساعات العمل',
    'availability': 'التوفر',
    
    // Secretary Dashboard
    'secretary_dashboard': 'لوحة تحكم السكرتيرة',
    'manage_appointments': 'إدارة المواعيد',
    'book_appointment': 'حجز موعد',
    'appointment_calendar': 'تقويم المواعيد',
    'patient_registration': 'تسجيل المريض',
    'appointments_today': 'مواعيد اليوم',
    'appointments_this_week': 'مواعيد هذا الأسبوع',
    'waiting_room': 'غرفة الانتظار',
    'checked_in': 'تسجيل الوصول',
    'check_in': 'تسجيل الوصول',
    'check_out': 'تسجيل الخروج',
    'waiting': 'في الانتظار',
    'in_consultation': 'في الاستشارة',
    'completed_today': 'مكتمل اليوم',
    
    // Admin specific
    'admin_dashboard': 'لوحة تحكم المسؤول',
    'system_overview': 'نظرة عامة على النظام',
    'user_management': 'إدارة المستخدمين',
    'doctor_management': 'إدارة الأطباء',
    'secretary_management': 'إدارة السكرتيرات',
    'add_doctor': 'إضافة طبيب',
    'add_secretary': 'إضافة سكرتيرة',
    'activate_account': 'تنشيط الحساب',
    'suspend_account': 'تعليق الحساب',
    'account_status': 'حالة الحساب',
    'access_control': 'تحكم الوصول',
    'permissions': 'الصلاحيات',
    'role': 'الدور',
    'last_login': 'آخر تسجيل دخول',
    'account_created': 'تم إنشاء الحساب',
    
    // Time periods
    'daily': 'يومي',
    'weekly': 'أسبوعي',
    'monthly': 'شهري',
    'yearly': 'سنوي',
    'custom_range': 'نطاق مخصص',
    'from_date': 'من تاريخ',
    'to_date': 'إلى تاريخ',
    'select_date': 'اختر التاريخ',
    'select_time': 'اختر الوقت',
    
    // Actions & Buttons
    'create': 'إنشاء',
    'update': 'تحديث',
    'remove': 'إزالة',
    'restore': 'استعادة',
    'archive': 'أرشفة',
    'unarchive': 'إلغاء الأرشفة',
    'duplicate': 'تكرار',
    'share': 'مشاركة',
    'copy': 'نسخ',
    'paste': 'لصق',
    'undo': 'تراجع',
    'redo': 'إعادة تنفيذ',
    'select': 'تحديد',
    'deselect': 'إلغاء التحديد',
    
    // Status messages
    'saved_successfully': 'تم الحفظ بنجاح',
    'deleted_successfully': 'تم الحذف بنجاح',
    'updated_successfully': 'تم التحديث بنجاح',
    'created_successfully': 'تم الإنشاء بنجاح',
    'operation_completed': 'اكتملت العملية',
    'please_wait': 'يرجى الانتظار',
    'processing': 'معالجة',
    'are_you_sure': 'هل أنت متأكد؟',
    'cannot_be_undone': 'لا يمكن التراجع عنه',
    'confirm_delete': 'تأكيد الحذف',
    'confirm_action': 'تأكيد الإجراء',
    
    // Pagination
    'page': 'صفحة',
    'of': 'من',
    'items_per_page': 'عناصر في الصفحة',
    'showing': 'عرض',
    'to': 'إلى',
    'results': 'نتائج',
    'first_page': 'الصفحة الأولى',
    'last_page': 'الصفحة الأخيرة',
    'no_data': 'لا توجد بيانات',
    'no_results_found': 'لم يتم العثور على نتائج',
    
    // Patient names (Arabic)
    'patient_name_1': 'محمد الغربي',
    'patient_name_2': 'أميرة بن سعيد',
    'patient_name_3': 'يوسف الحمدي',
    'patient_name_4': 'سلمى الطرابلسي',
    'patient_name_5': 'كريم بوزيد',
    'patient_name_6': 'ليلى منصور',
    'patient_name_7': 'أحمد التواتي',
    
    // Patient job titles
    'job_teacher': 'مدرس',
    'job_pharmacist': 'صيدلانية',
    'job_engineer': 'مهندس',
    'job_merchant': 'تاجرة',
    'job_lawyer': 'محامي',
    'job_nurse': 'ممرضة',
    'job_accountant': 'محاسب',
    
    // Patient addresses
    'address_tunis_bourguiba': 'شارع بورقيبة، تونس',
    'address_sousse_nov7': 'شارع 7 نوفمبر، سوسة',
    'address_sfax_republique': 'نهج الجمهورية، صفاقس',
    'address_monastir_liberte': 'شارع الحرية، المنستير',
    'address_bizerte_thameur': 'نهج الحبيب ثامر، بنزرت',
    'address_nabeul_independence': 'شارع الاستقلال، نابل',
    'address_gabes_principale': 'الشارع الرئيسي، قابس',
    
    // Medical conditions/diseases
    'disease_hypertension': 'ارتفاع ضغط الدم',
    'disease_diabetes_type2': 'داء السكري النوع 2',
    'disease_chronic_migraine': 'الصداع النصفي المزمن',
    'disease_arthritis': 'التهاب المفاصل',
    'disease_asthma': 'الربو',
    'disease_thyroid': 'اضطرابات الغدة الدرقية',
    
    // Consultation notes examples
    'note_patient_stable': 'المريض في حالة مستقرة، فحص بعد 3 أشهر',
    'note_crisis_decreasing': 'تناقص في تكرار الأزمات',
    'note_regular_followup': 'يوصى بالمتابعة المنتظمة',
    
    // Prescriptions examples
    'prescription_metformin': 'ميتفورمين 500 ملغ - مرتين في اليوم',
    'prescription_ramipril': 'راميبريل 5 ملغ - مرة واحدة في اليوم',
    'prescription_sumatriptan': 'سوماتريبتان 50 ملغ - في حالة الأزمة',
    
    // Analysis types
    'analysis_glucose': 'فحص السكر على الريق',
    'analysis_hba1c': 'تحليل HbA1c',
    'analysis_cholesterol': 'فحص الدهون',
    'analysis_blood_count': 'تعداد الدم الكامل',
    
    // Profile page specific
    'edit_profile': 'تعديل الملف الشخصي',
    'profile_picture': 'صورة الملف الشخصي',
    'upload_picture': 'تحميل صورة',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'full_name': 'الاسم الكامل',
    'bio': 'السيرة الذاتية',
    'about_me': 'نبذة عني',
    'professional_title': 'المسمى الوظيفي',
    'medical_specialty': 'التخصص الطبي',
    'practice_since': 'يمارس منذ',
    'consultation_price': 'سعر الاستشارة',
    'office_phone': 'هاتف العيادة',
    'mobile_phone': 'الهاتف المحمول',
    'office_hours': 'ساعات العمل',
    'monday_friday': 'الاثنين - الجمعة',
    'saturday': 'السبت',
    'closed': 'مغلق',
    'morning': 'صباحاً',
    'afternoon': 'بعد الظهر',
    'evening': 'مساءً',
  },
  
  en: {
    // Common
    'welcome': 'Welcome',
    'logout': 'Logout',
    'profile': 'Profile',
    'settings': 'Settings',
    'search': 'Search',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'close': 'Close',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'actions': 'Actions',
    'status': 'Status',
    'name': 'Name',
    'date': 'Date',
    'time': 'Time',
    'type': 'Type',
    'details': 'Details',
    'description': 'Description',
    'notes': 'Notes',
    'filter': 'Filter',
    'sort': 'Sort',
    'export': 'Export',
    'import': 'Import',
    'download': 'Download',
    'upload': 'Upload',
    'print': 'Print',
    
    // Navigation
    'dashboard': 'Dashboard',
    'appointments': 'Appointments',
    'consultations': 'Consultations',
    'patients': 'Patients',
    'revenue': 'Revenue',
    'chat': 'Messages',
    'calendar': 'Calendar',
    'reports': 'Reports',
    'statistics': 'Statistics',
    
    // User & Auth
    'email': 'Email',
    'password': 'Password',
    'sign_in': 'Sign in',
    'sign_up': 'Sign up',
    'sign_out': 'Sign out',
    'forgot_password': 'Forgot password?',
    'remember_me': 'Remember me',
    'medical_management': 'Smart medical practice management',
    'no_account': 'Don\'t have an account?',
    'create_doctor_account': 'Create Doctor Account',
    'create_secretary_account': 'Create Secretary Account',
    'demo_accounts': 'Demo accounts:',
    'admin': 'Admin',
    'doctor': 'Doctor',
    'secretary': 'Secretary',
    
    // Languages
    'language': 'Language',
    'french': 'Français',
    'arabic': 'العربية',
    'english': 'English',
    'change_language': 'Change language',
    
    // Calendar / Appointments
    'Planning_of':'Planning of',
    'rendez-vous_programmés':'appointments scheduled',
    'new_appointment': 'New Appointment',
    'appointment_details': 'Appointment Details',
    'today_appointments': 'Today\'s Appointments',
    'upcoming_appointments': 'Upcoming Appointments',
    'past_appointments': 'Past Appointments',
    'appointment_time': 'Appointment Time',
    'appointment_type': 'Appointment Type',
    'appointment_status': 'Appointment Status',
    'patient_name': 'Patient Name',
    'patient_phone': 'Phone',
    'patient_email': 'Patient Email',
    'birth_date': 'Birth Date',
    'age': 'Age',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'address': 'Address',
    'profession': 'Profession',
    'country': 'Country',
    'region': 'Region',
    'city': 'City',
    'select_country': 'Select a country',
    'select_region': 'Select a region',
    'select_profession': 'Select a profession',
    'select_first_country': 'Select a country first',
    'please_select_country_first': 'Please select a country first',
    'regions_available': 'region(s) available for',
    'professions_available': 'profession(s) available',
    'selected': 'Selected',
    
    // Appointment Types & Status
    'consultation': 'Consultation',
    'control': 'Follow-up',
    'follow_up': 'Follow-up',
    'emergency': 'Emergency',
    'confirmed': 'Confirmed',
    'pending': 'Pending',
    'cancelled': 'Cancelled',
    'completed': 'Completed',
    'no_show': 'No Show',
    'confirm_appointment': 'Confirm Appointment',
    'cancel_appointment': 'Cancel Appointment',
    'reschedule_appointment': 'Reschedule Appointment',
    
    // Countries
    'tunisia': 'Tunisia',
    'libya': 'Libya',
    'algeria': 'Algeria',
    'morocco': 'Morocco',
    'egypt': 'Egypt',
    'other': 'Other',
    
    // Patients
    'patient_list': 'Patient List',
    'patient_info': 'Patient Info',
    'patient_details': 'Patient Details',
    'medical_history': 'Medical History',
    'add_patient': 'Add Patient',
    'edit_patient': 'Edit Patient',
    'delete_patient': 'Delete Patient',
    'total_patients': 'Total Patients',
    'new_patients': 'New Patients',
    'active_patients': 'Active Patients',
    'patient_since': 'Patient since',
    'last_visit': 'Last visit',
    'next_appointment': 'Next appointment',
    'no_patients': 'No patients',
    'search_patients': 'Search patients',
    'patient_added': 'Patient added successfully',
    'patient_updated': 'Patient updated',
    'patient_deleted': 'Patient deleted',
    
    // Consultations
    'consultation_notes': 'Consultation Notes',
    'diagnosis': 'Diagnosis',
    'prescription': 'Prescription',
    'treatment': 'Treatment',
    'symptoms': 'Symptoms',
    'vital_signs': 'Vital Signs',
    'blood_pressure': 'Blood Pressure',
    'heart_rate': 'Heart Rate',
    'temperature': 'Temperature',
    'weight': 'Weight',
    'height': 'Height',
    'start_consultation': 'Start Consultation',
    'end_consultation': 'End Consultation',
    'save_consultation': 'Save Consultation',
    'consultation_history': 'Consultation History',
    'no_consultations': 'No consultations',
    'ai_assistant': 'AI Assistant',
    'ai_suggestions': 'AI Suggestions',
    
    // Revenue / Financial
    'total_revenue': 'Total Revenue',
    'monthly_revenue': 'Monthly Revenue',
    'daily_revenue': 'Daily Revenue',
    'yearly_revenue': 'Yearly Revenue',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'credit_card': 'Credit Card',
    'bank_transfer': 'Bank Transfer',
    'insurance': 'Insurance',
    'amount': 'Amount',
    'paid': 'Paid',
    'unpaid': 'Unpaid',
    'partial': 'Partial',
    'payment_status': 'Payment Status',
    'invoice': 'Invoice',
    'receipt': 'Receipt',
    'generate_invoice': 'Generate Invoice',
    'revenue_statistics': 'Revenue Statistics',
    'monthly_comparison': 'Monthly Comparison',
    'payment_history': 'Payment History',
    
    // Chat / Messages
    'messages': 'Messages',
    'new_message': 'New Message',
    'send_message': 'Send',
    'type_message': 'Type a message...',
    'attach_file': 'Attach File',
    'no_messages': 'No messages',
    'chat_with_doctor': 'Chat with doctor',
    'chat_with_secretary': 'Chat with secretary',
    'chat_with_admin': 'Chat with admin',
    'online': 'Online',
    'offline': 'Offline',
    'typing': 'Typing...',
    'seen': 'Seen',
    'delivered': 'Delivered',
    'sent': 'Sent',
    'message_deleted': 'Message deleted',
    'delete_message': 'Delete message',
    'edit_message': 'Edit message',
    'file_attached': 'File attached',
    
    // Dashboard Stats
    'appointments_overview': 'Appointments Overview',
    'recent_patients': 'Recent Patients',
    'patient_satisfaction': 'Patient Satisfaction',
    'pending_appointments': 'Pending Appointments',
    'confirmed_today': 'Confirmed Today',
    'total_doctors': 'Total Doctors',
    'active_users': 'Active Users',
    'system_revenue': 'System Revenue',
    'doctors_management': 'Doctors Management',
    
    // Time & Dates
    'today': 'Today',
    'yesterday': 'Yesterday',
    'tomorrow': 'Tomorrow',
    'this_week': 'This week',
    'this_month': 'This month',
    'this_year': 'This year',
    'last_week': 'Last week',
    'last_month': 'Last month',
    'last_year': 'Last year',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    
    // Status & Actions
    'active': 'Active',
    'inactive': 'Inactive',
    'suspended': 'Suspended',
    'view_details': 'View Details',
    'show_more': 'Show more',
    'show_less': 'Show less',
    'select_all': 'Select all',
    'deselect_all': 'Deselect all',
    'refresh': 'Refresh',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'continue': 'Continue',
    'finish': 'Finish',
    'submit': 'Submit',
    'reset': 'Reset',
    'clear': 'Clear',
    
    // Notifications
    'notifications': 'Notifications',
    'no_notifications': 'No notifications',
    'mark_as_read': 'Mark as read',
    'mark_all_as_read': 'Mark all as read',
    'new_notification': 'New notification',
    
    // Errors & Validation
    'field_required': 'This field is required',
    'invalid_email': 'Invalid email',
    'invalid_phone': 'Invalid phone number',
    'password_too_short': 'Password too short',
    'passwords_dont_match': 'Passwords don\'t match',
    'something_went_wrong': 'Something went wrong',
    'try_again': 'Try again',
    'operation_successful': 'Operation successful',
    'operation_failed': 'Operation failed',
    
    // Misc
    'welcome_back': 'Welcome back',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'have_a_nice_day': 'Have a nice day',
    'dr': 'Dr.',
    'mr': 'Mr.',
    'mrs': 'Mrs.',
    'ms': 'Ms.',
    
    // Calendar specific
    'no_appointments': 'No appointments',
    'click_new_appointment_to_add': 'Click "New Appointment" to add a patient',
    'edit_appointment': 'Edit appointment',
    'appointment_saved': 'Appointment saved successfully',
    'new_patient': 'New patient',
    'existing_patient': 'Existing patient',
    'search_existing_patient': 'Search for existing patient...',
    'payment_type': 'Payment type',
    'payment_normal': 'Normal',
    'payment_cnam': 'CNAM',
    'payment_insurance': 'Insurance',
    'payment_free': 'Free',
    'tariff': 'Tariff',
    'amount_paid_label': 'Amount paid',
    'delete_appointment_confirm': 'Do you really want to delete this appointment?',
    'appointment_deleted': 'Appointment deleted',
    'appointment_confirmed': 'Appointment confirmed',
    
    // Consultations specific
    'consultations_confirmed': 'Confirmed consultations',
    'confirmed_appointments_list': 'List of confirmed appointments, sorted from newest to oldest',
    'patient_file': 'Patient file',
    'update_patient': 'Edit',
    'save_changes': 'Save',
    'return': 'Back',
    'years_old': 'years old',
    'chronic_diseases': 'Chronic diseases',
    'medical_history': 'Medical history',
    'previous_consultations': 'Previous consultations',
    'new_consultation': 'New consultation',
    'prescription_label': 'Prescription',
    'analysis_requested': 'Requested analyses',
    'imaging_requested': 'Requested imaging',
    'clinical_notes': 'Clinical notes',
    'save_consultation': 'Save consultation',
    'consultation_saved': 'Consultation saved successfully',
    'referral_letter': 'Referral letter',
    'files_attached': 'Attached files',
    'add_file': 'Add file',
    'no_files': 'No attached files',
    'click_add_file': 'Click "Add file" to start',
    'view': 'View',
    'rename': 'Rename',
    'file_renamed': 'File renamed successfully',
    'file_deleted': 'File deleted successfully',
    'delete_file_confirm': 'Are you sure you want to delete this file?',
    'patient_info_updated': 'Patient information updated successfully',
    
    // Professions
    'select_profession_placeholder': 'Select a profession',
    'medical_health_sector': 'Medical & Health Sector',
    'profession_doctor': 'Doctor',
    'profession_nurse': 'Nurse',
    'profession_pharmacist': 'Pharmacist',
    'profession_dentist': 'Dentist',
    'education_sector': 'Education Sector',
    'profession_teacher': 'Teacher',
    'profession_professor': 'Professor',
    'profession_student': 'Student',
    'engineering_tech_sector': 'Engineering & Technology',
    'profession_engineer': 'Engineer',
    'profession_developer': 'Developer',
    'profession_technician': 'Technician',
    'business_management_sector': 'Business & Management',
    'profession_manager': 'Manager',
    'profession_accountant': 'Accountant',
    'profession_entrepreneur': 'Entrepreneur',
    'public_services_sector': 'Public Services',
    'profession_civil_servant': 'Civil Servant',
    'profession_police': 'Police Officer',
    'profession_firefighter': 'Firefighter',
    'arts_culture_sector': 'Arts & Culture',
    'profession_artist': 'Artist',
    'profession_musician': 'Musician',
    'profession_writer': 'Writer',
    'other_professions': 'Other Professions',
    'profession_retired': 'Retired',
    'profession_housewife': 'Homemaker',
    'profession_unemployed': 'Unemployed',
    'profession_other': 'Other',
    
    // Countries detailed
    'maghreb_countries': 'Pays du Maghreb',
    'middle_east_countries': 'Pays du Moyen-Orient',
    'european_countries': 'Pays Européens',
    'tunisia_full': 'Tunisie - République Tunisienne',
    'algeria_full': 'Algérie - République Algérienne',
    'morocco_full': 'Maroc - Royaume du Maroc',
    'libya_full': 'Libye - État de Libye',
    'mauritania_full': 'Mauritanie - République Islamique de Mauritanie',
    
    // Regions
    'tunisia_regions': 'Régions de Tunisie',
    'region_tunis': 'Tunis',
    'region_ariana': 'Ariana',
    'region_ben_arous': 'Ben Arous',
    'region_manouba': 'Manouba',
    'region_sfax': 'Sfax',
    'region_sousse': 'Sousse',
    'region_nabeul': 'Nabeul',
    
    // Consultation details
    'consultation_date': 'Date de consultation',
    'consultation_type': 'Type de consultation',
    'reason_for_visit': 'Motif de visite',
    'examination': 'Examen',
    'treatment_plan': 'Plan de traitement',
    'follow_up_date': 'Date de suivi',
    'medications': 'Médicaments',
    'dosage': 'Dosage',
    'frequency': 'Fréquence',
    'duration': 'Durée',
    'instructions': 'Instructions',
    'side_effects': 'Effets secondaires',
    'allergies': 'Allergies',
    'current_medications': 'Médicaments actuels',
    'medical_conditions': 'Conditions médicales',
    'family_history': 'Antécédents familiaux',
    'social_history': 'Antécédents sociaux',
    'surgical_history': 'Antécédents chirurgicaux',
    
    // AI Assistant
    'ask_ai': 'Demander à l\'IA',
    'ai_analyzing': 'IA en cours d\'analyse...',
    'ai_suggestion': 'Suggestion IA',
    'ai_diagnosis_help': 'Aide au diagnostic',
    'ai_treatment_suggestions': 'Suggestions de traitement',
    'ai_drug_interactions': 'Interactions médicamenteuses',
    'ai_medical_references': 'Références médicales',
    'type_your_question': 'Tapez votre question...',
    'send': 'Envoyer',
    
    // File management
    'file_name': 'Nom du fichier',
    'file_size': 'Taille',
    'file_type': 'Type',
    'uploaded_date': 'Date d\'upload',
    'uploaded_by': 'Uploadé par',
    'download_file': 'Télécharger',
    'delete_file': 'Supprimer',
    'rename_file': 'Renommer',
    'preview_file': 'Prévisualiser',
    'upload_file': 'Téléverser un fichier',
    'drag_drop_files': 'Glissez-déposez vos fichiers ici',
    'or_click_to_browse': 'ou cliquez pour parcourir',
    'supported_formats': 'Formats supportés',
    'max_file_size': 'Taille maximale',
    
    // Patients View
    'all_patients': 'Tous les patients',
    'patients_list': 'Liste des patients',
    'patient_card': 'Carte patient',
    'patient_number': 'N° Patient',
    'registration_date': 'Date d\'inscription',
    'total_consultations': 'Total consultations',
    'last_consultation': 'Dernière consultation',
    'patient_status': 'Statut patient',
    'contact_info': 'Informations de contact',
    'emergency_contact': 'Contact d\'urgence',
    'insurance_info': 'Informations d\'assurance',
    'insurance_number': 'N° d\'assurance',
    'insurance_provider': 'Fournisseur d\'assurance',
    'policy_number': 'N° de police',
    'expiry_date': 'Date d\'expiration',
    
    // Revenue View
    'revenue_overview': 'Aperçu des revenus',
    'total_earnings': 'Gains totaux',
    'this_month_revenue': 'Revenus du mois',
    'last_month_revenue': 'Revenus mois dernier',
    'revenue_growth': 'Croissance des revenus',
    'payment_received': 'Paiement reçu',
    'payment_pending': 'Paiement en attente',
    'payment_details': 'Détails du paiement',
    'transaction_history': 'Historique des transactions',
    'transaction_date': 'Date de transaction',
    'transaction_type': 'Type de transaction',
    'transaction_amount': 'Montant',
    'transaction_id': 'ID Transaction',
    'payment_for': 'Paiement pour',
    'revenue_by_month': 'Revenus par mois',
    'revenue_by_payment_type': 'Revenus par type de paiement',
    'revenue_statistics_detailed': 'Statistiques détaillées des revenus',
    'average_per_consultation': 'Moyenne par consultation',
    'consultations_count': 'Nombre de consultations',
    'paid_consultations': 'Consultations payées',
    'unpaid_consultations': 'Consultations non payées',
    
    // Profile & Settings
    'personal_information': 'Informations personnelles',
    'professional_information': 'Informations professionnelles',
    'account_settings': 'Paramètres du compte',
    'security_settings': 'Paramètres de sécurité',
    'change_password': 'Changer le mot de passe',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'update_profile': 'Mettre à jour le profil',
    'profile_updated': 'Profil mis à jour avec succès',
    'password_updated': 'Mot de passe mis à jour',
    'specialty': 'Spécialité',
    'license_number': 'N° de licence',
    'years_of_experience': 'Années d\'expérience',
    'education': 'Formation',
    'certifications': 'Certifications',
    'languages_spoken': 'Langues parlées',
    'clinic_address': 'Adresse du cabinet',
    'consultation_fees': 'Honoraires de consultation',
    'working_hours': 'Heures de travail',
    'availability': 'Disponibilité',
    
    // Secretary Dashboard
    'secretary_dashboard': 'Tableau de bord Secrétaire',
    'manage_appointments': 'Gérer les rendez-vous',
    'book_appointment': 'Prendre un rendez-vous',
    'appointment_calendar': 'Calendrier des rendez-vous',
    'patient_registration': 'Inscription patient',
    'appointments_today': 'Rendez-vous aujourd\'hui',
    'appointments_this_week': 'RDV cette semaine',
    'waiting_room': 'Salle d\'attente',
    'checked_in': 'Enregistré',
    'check_in': 'Enregistrer',
    'check_out': 'Libérer',
    'waiting': 'En attente',
    'in_consultation': 'En consultation',
    'completed_today': 'Terminés aujourd\'hui',
    
    // Admin specific
    'admin_dashboard': 'Tableau de bord Admin',
    'system_overview': 'Vue d\'ensemble du système',
    'user_management': 'Gestion des utilisateurs',
    'doctor_management': 'Gestion des médecins',
    'secretary_management': 'Gestion des secrétaires',
    'add_doctor': 'Ajouter un médecin',
    'add_secretary': 'Ajouter une secrétaire',
    'activate_account': 'Activer le compte',
    'suspend_account': 'Suspendre le compte',
    'account_status': 'Statut du compte',
    'access_control': 'Contrôle d\'accès',
    'permissions': 'Permissions',
    'role': 'Rôle',
    'last_login': 'Dernière connexion',
    'account_created': 'Compte créé',
    
    // Time periods
    'daily': 'Quotidien',
    'weekly': 'Hebdomadaire',
    'monthly': 'Mensuel',
    'yearly': 'Annuel',
    'custom_range': 'Période personnalisée',
    'from_date': 'De',
    'to_date': 'À',
    'select_date': 'Sélectionner une date',
    'select_time': 'Sélectionner l\'heure',
    
    // Actions & Buttons
    'create': 'Créer',
    'update': 'Mettre à jour',
    'remove': 'Retirer',
    'restore': 'Restaurer',
    'archive': 'Archiver',
    'unarchive': 'Désarchiver',
    'duplicate': 'Dupliquer',
    'share': 'Partager',
    'copy': 'Copier',
    'paste': 'Coller',
    'undo': 'Annuler',
    'redo': 'Refaire',
    'select': 'Sélectionner',
    'deselect': 'Désélectionner',
    
    // Status messages
    'saved_successfully': 'Enregistré avec succès',
    'deleted_successfully': 'Supprimé avec succès',
    'updated_successfully': 'Mis à jour avec succès',
    'created_successfully': 'Créé avec succès',
    'operation_completed': 'Opération terminée',
    'please_wait': 'Veuillez patienter',
    'processing': 'Traitement en cours',
    'are_you_sure': 'Êtes-vous sûr ?',
    'cannot_be_undone': 'Cette action ne peut pas être annulée',
    'confirm_delete': 'Confirmer la suppression',
    'confirm_action': 'Confirmer l\'action',
    
    // Pagination
    'page': 'Page',
    'of': 'de',
    'items_per_page': 'Éléments par page',
    'showing': 'Affichage',
    'to': 'to',
    'results': 'results',
    'first_page': 'First page',
    'last_page': 'Last page',
    'no_data': 'No data',
    'no_results_found': 'No results found',
    
    // Patient names (English - keeping French names but translatable)
    'patient_name_1': 'Mohamed Gharbi',
    'patient_name_2': 'Amira Ben Said',
    'patient_name_3': 'Youssef Hamdi',
    'patient_name_4': 'Salma Trabelsi',
    'patient_name_5': 'Karim Bouzid',
    'patient_name_6': 'Leila Mansour',
    'patient_name_7': 'Ahmed Touati',
    
    // Patient job titles
    'job_teacher': 'Teacher',
    'job_pharmacist': 'Pharmacist',
    'job_engineer': 'Engineer',
    'job_merchant': 'Merchant',
    'job_lawyer': 'Lawyer',
    'job_nurse': 'Nurse',
    'job_accountant': 'Accountant',
    
    // Patient addresses
    'address_tunis_bourguiba': 'Bourguiba Avenue, Tunis',
    'address_sousse_nov7': '7 November Boulevard, Sousse',
    'address_sfax_republique': 'Republic Street, Sfax',
    'address_monastir_liberte': 'Liberty Avenue, Monastir',
    'address_bizerte_thameur': 'Habib Thameur Street, Bizerte',
    'address_nabeul_independence': 'Independence Avenue, Nabeul',
    'address_gabes_principale': 'Main Street, Gabès',
    
    // Medical conditions/diseases
    'disease_hypertension': 'Hypertension',
    'disease_diabetes_type2': 'Type 2 Diabetes',
    'disease_chronic_migraine': 'Chronic Migraine',
    'disease_arthritis': 'Arthritis',
    'disease_asthma': 'Asthma',
    'disease_thyroid': 'Thyroid Disorders',
    
    // Consultation notes examples
    'note_patient_stable': 'Patient stable, check-up in 3 months',
    'note_crisis_decreasing': 'Decreasing frequency of crises',
    'note_regular_followup': 'Regular follow-up recommended',
    
    // Prescriptions examples
    'prescription_metformin': 'Metformin 500mg - 2x/day',
    'prescription_ramipril': 'Ramipril 5mg - 1x/day',
    'prescription_sumatriptan': 'Sumatriptan 50mg - as needed for crisis',
    
    // Analysis types
    'analysis_glucose': 'Fasting Blood Glucose',
    'analysis_hba1c': 'HbA1c',
    'analysis_cholesterol': 'Lipid Panel',
    'analysis_blood_count': 'Complete Blood Count',
    
    // Profile page specific
    'edit_profile': 'Edit Profile',
    'profile_picture': 'Profile Picture',
    'upload_picture': 'Upload Picture',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'full_name': 'Full Name',
    'bio': 'Biography',
    'about_me': 'About Me',
    'professional_title': 'Professional Title',
    'medical_specialty': 'Medical Specialty',
    'practice_since': 'Practicing Since',
    'consultation_price': 'Consultation Price',
    'office_phone': 'Office Phone',
    'mobile_phone': 'Mobile Phone',
    'office_hours': 'Office Hours',
    'monday_friday': 'Monday - Friday',
    'saturday': 'Saturday',
    'closed': 'Closed',
    'morning': 'Morning',
    'afternoon': 'Afternoon',
    'evening': 'Evening',
  },
};