/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hbkladdxlwfgwgagajrf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhia2xhZGR4bHdmZ3dnYWdhanJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0MzcxMTIsImV4cCI6MjA4MTAxMzExMn0.SGSIBC4qMkjwCoYu-v6X-SNG0M1SOZ-3TNXQyRiIkq4"